{% set version = "2.0.3" %}
{% set checksum = "05e986a5c7327796dad742182b2d10805a8d4f511ad090da0490f146c1ff7a8c" %}
{% set checktype = "sha256" %}

package:
    name: sparsehash
    version: {{ version }}

source:
    fn: sparsehash-{{ version }}.tar.gz
    url: https://github.com/sparsehash/sparsehash/archive/sparsehash-{{ version }}.tar.gz
    {{ checktype }}: {{ checksum }}

build:
    number: 1000
    features:
        - vc9   # [win and py27]
        - vc10  # [win and py34]
        - vc14  # [win and py35]

requirements:
    build:
        - python  # [win]
        - vc 9  # [win and py27]
        - vc 10  # [win and py34]
        - vc 14  # [win and py35]
        - toolchain
        - pkg-config  # [not win]
    run:
        - vc 9  # [win and py27]
        - vc 10  # [win and py34]
        - vc 14  # [win and py35]

test:
    commands:
        - test -f "${PREFIX}/lib/pkgconfig/libsparsehash.pc"  # [unix]
        - test -r "${PREFIX}/include/sparsehash"  # [unix]
        - test -r "${PREFIX}/include/sparsehash/internal"  # [unix]
        - test -r "${PREFIX}/include/google/"  # [unix]
        - test -r "${PREFIX}/include/google/sparsehash"  # [unix]
        - if not exist %LIBRARY_INC%\sparsehash exit 1  # [win]
        - if not exist %LIBRARY_INC%\sparsehash\internal exit 1  # [win]
        - if not exist %LIBRARY_INC%\google exit 1  # [win]
        - if not exist %LIBRARY_INC%\google\sparsehash exit 1  # [win]

about:
    home: https://github.com/sparsehash/sparsehash
    license: BSD 3-Clause
    summary: "Sparsehash libarry is an extremely memory-efficient hash_map implementation."

extra:
    recipe-maintainers:
        - vgauthier
        - edisongustavo
