{% set version = "2.0.4" %}

package:
  name: sparsehash
  version: {{ version }}

source:
  url: https://github.com/sparsehash/sparsehash/archive/sparsehash-{{ version }}.tar.gz
  sha256: 8cd1a95827dfd8270927894eb77f62b4087735cbede953884647f16c521c7e58

build:
  number: 0

requirements:
  build:
    - make  # [not win]
    - pkg-config  # [not win]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f "${PREFIX}/lib/pkgconfig/libsparsehash.pc"  # [not win]
    - test -r "${PREFIX}/include/sparsehash"  # [not win]
    - test -r "${PREFIX}/include/sparsehash/internal"  # [not win]
    - test -r "${PREFIX}/include/google/"  # [not win]
    - test -r "${PREFIX}/include/google/sparsehash"  # [not win]
    - if not exist %LIBRARY_INC%\sparsehash exit 1  # [win]
    - if not exist %LIBRARY_INC%\sparsehash\internal exit 1  # [win]
    - if not exist %LIBRARY_INC%\google exit 1  # [win]
    - if not exist %LIBRARY_INC%\google\sparsehash exit 1  # [win]

about:
  home: https://github.com/sparsehash/sparsehash
  license: BSD-3-Clause
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: "Sparsehash library is an extremely memory-efficient hash_map implementation."

extra:
  recipe-maintainers:
    - vgauthier
    - edisongustavo
    - benjaminrwilson
