travis:
  secure:
    BINSTAR_TOKEN: R4rlIdq1HsfUQlQJkWc5hn8JPCx2vtTH3Du71Wd5DWnVHULZYgEfBhjYWoOlEVdrm8nWjIVS+b83bpJo5Zo37vv81gobnFAb+tN2VKig7LRD3c9rj12CqG+E1Wy19VssVJEHAZV/C7/y9QavJ3wjevMEqcozyy3LuHlk5dz57gSWXmPc+352J5nRP53ZdhH581yYN2IwTMQdGcIX8mCNhVj74qTLBYKvP39Vmpp7TxOWKQi/UI1paAEztjTa7bOdztdj2T7auJ1dCuZhWmvaVDC0hWru73+CqmLTYULsU5UfTBoFhjM2kGbdngTfEKhn3B8ay/j98hUxccmTX8C9TF/dBWDmD8iVz4sSH7bA9lBJtsSYdghGrSD4CHHi8mRXEbJ5etf78PvORpE2sxjEgx5BhyGC/gikeNx9Evg2JcPmjLrJUy6Gx79Ki/Xf+NtAhdGng8D/twtBszHJ8ppybYUJcgTj1O8R0x+1KZnRK+hxZ659XpSpLn3FkdmF8YOhg4/yDyG/ytfvGlOazzJwt0rO3wjeHsBK9GyZAOLvWG1cXfNazojqX5blLIvgzkaMvl7M3IwHe2e62UFz8dCUEekmJ3vfms5GWMkKNPKFouXfdav5CUAvBzCBI99ZsHRLMyy1flcxz6QES/tAsxCC8JTY4B11FX6nj0MecUQxWbg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
